"""status column added

Revision ID: 75f3492189ef
Revises: fec2d45ffb5d
Create Date: 2025-03-01 00:33:06.270951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f3492189ef'
down_revision: Union[str, None] = 'fec2d45ffb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_todos_status'), 'todos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_status'), table_name='todos')
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
